### PR TITLE
fix: nil check in post

### LINKED ISSUE #114: [Bug]: Submitting transaction with the "--fee-granter" flag fails during simulate because of panic in feemarket PostHandle()
When submitting transaction with the "--fee-granter" flag, an unexpected error is raised. For example:

`gaiad tx bank send wallet2 cosmos1p5238sjdqttvswa0zx2awvacjy98yrh3wxzkem 10stake --from wallet2 --fee-granter cosmos1e35997edcs7rc28sttwd436u0e83jw6ct4f3f4`

(Also, notice at the bottom of the stack trace this line, which seems weird as well: "**With gas wanted: '18446744073709551615'** ")

Error:

`Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: runtime error: invalid memory address or nil pointer dereference
stack:
goroutine 793 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3({0x27c7b60, 0x5174780})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/recovery.go:71 +0x25
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5({0x27c7b60?, 0x5174780?})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/recovery.go:39 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x27c7b60, 0x5174780}, 0x3e8?)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/recovery.go:28 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x27c7b60, 0x5174780}, 0xc004e32480?)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/recovery.go:33 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/baseapp.go:646 +0x138
panic({0x27c7b60?, 0x5174780?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
math/big.(*Int).Sign(...)
	/usr/local/go/src/math/big/int.go:49
cosmossdk.io/math.Int.IsZero(...)
	/home/dusan/go/pkg/mod/cosmossdk.io/math@v1.3.0/int.go:232
github.com/cosmos/cosmos-sdk/types.Coin.IsZero(...)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/coin.go:61
github.com/cosmos/cosmos-sdk/types.removeZeroCoins({0xc004cd1590?, 0x4186db?, 0x15?})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/coin.go:793 +0x30
github.com/cosmos/cosmos-sdk/types.sanitizeCoins({0xc004cd1590?, 0x18?, 0x7ff257a6bf18?})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/coin.go:190 +0x18
github.com/cosmos/cosmos-sdk/types.NewCoins({0xc004cd1590?, 0x14?, 0x15?})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/coin.go:181 +0x1f
github.com/skip-mev/feemarket/x/feemarket/post.FeeMarketDeductDecorator.DeductFeeAndTip({{_, _}, {_, _}, {_, _}, {_, _}}, {{0x3964220, 0x5317e40}, ...}, ...)
	/home/dusan/go/pkg/mod/github.com/skip-mev/feemarket@v1.0.0-sdk47/x/feemarket/post/fee.go:162 +0x325
github.com/skip-mev/feemarket/x/feemarket/post.FeeMarketDeductDecorator.PostHandle({{_, _}, {_, _}, {_, _}, {_, _}}, {{0x3964220, 0x5317e40}, ...}, ...)
	/home/dusan/go/pkg/mod/github.com/skip-mev/feemarket@v1.0.0-sdk47/x/feemarket/post/fee.go:113 +0xac5
github.com/cosmos/cosmos-sdk/types.ChainPostDecorators.func1({{0x3964220, 0x5317e40}, {0x397cd30, 0xc004c94f00}, {{0xb, 0x0}, {0xc004a9411c, 0x4}, 0x45, {0x18d94c1f, ...}, ...}, ...}, ...)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/handler.go:72 +0x13e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0003b65a0, 0x2, {0xc002986dc0, 0x121, 0x140})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/baseapp.go:760 +0xfb3
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/test_helpers.go:25
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x397ee40, 0xc000748d60}, 0x0, {0xc000da1540, 0x4}, {0x3995380, 0xc000bb7450}, ...}, ...}, ...)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/x/auth/tx/service.go:132 +0x12f
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x2a9b820, 0xc0003b74a0}, {0x39643e0, 0xc002c56848}, 0xc002c310e0, 0x0)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/types/tx/service.pb.go:1416 +0x1a6
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x3964220, 0x5317e40}, {0x397cd30, 0xc004c94c80}, {{0xb, 0x0}, {0xc004a9411c, 0x4}, 0x45, {0x18d94c1f, ...}, ...}, ...}, ...)
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/grpcrouter.go:82 +0x184
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc0003b65a0, 0xc002685110, {{0xc0032bc000, 0x124, 0x280}, {0xc0045a1bf0, 0x23}, 0x45, 0x0})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/abci.go:698 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc0003b65a0, {{0xc0032bc000, 0x124, 0x280}, {0xc0045a1bf0, 0x23}, 0x45, 0x0})
	/home/dusan/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/abci.go:545 +0x776
github.com/cometbft/cometbft/abci/client.(*localClient).QuerySync(0xc003290240, {{0xc0032bc000, 0x124, 0x280}, {0xc0045a1bf0, 0x23}, 0x0, 0x0})
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/abci/client/local_client.go:259 +0x163
github.com/cometbft/cometbft/proxy.(*appConnQuery).QuerySync(0xc000ccc288, {{0xc0032bc000, 0x124, 0x280}, {0xc0045a1bf0, 0x23}, 0x0, 0x0})
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/proxy/app_conn.go:193 +0x1ca
github.com/cometbft/cometbft/rpc/core.ABCIQuery(0xc0006ab140?, {0xc0045a1bf0?, 0x4?}, {0xc0032bc000?, 0x2?, 0x2?}, 0x0?, 0x13?)
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/rpc/core/abci.go:20 +0x9a
reflect.Value.call({0x2825c20?, 0x32e5238?, 0x2bced20?}, {0x2be03fa, 0x4}, {0xc000f7f380, 0x5, 0x5?})
	/usr/local/go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0x2825c20?, 0x32e5238?, 0x29b?}, {0xc000f7f380?, 0x2bced20?, 0xc00471d510?})
	/usr/local/go/src/reflect/value.go:380 +0xb9
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3({0x3954460, 0xc004cd05e8}, 0xc002c52a20)
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/rpc/jsonrpc/server/http_json_handler.go:108 +0xce6
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4({0x3954460?, 0xc004cd05e8?}, 0x40?)
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/rpc/jsonrpc/server/http_json_handler.go:140 +0x42
net/http.HandlerFunc.ServeHTTP(0xc0015d05b0?, {0x3954460?, 0xc004cd05e8?}, 0xc00471d990?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x0?, {0x3954460, 0xc004cd05e8}, 0xc002c52a20)
	/usr/local/go/src/net/http/server.go:2683 +0x1ad
github.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x3934040?, 0xc0015d05b0?}, 0xd?}, {0x3954460, 0xc004cd05e8}, 0xc002c52a20)
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/rpc/jsonrpc/server/http_server.go:256 +0xfb
github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x3946aa0, 0xc001068000}, 0xc002c52a20)
	/home/dusan/go/pkg/mod/github.com/cometbft/cometbft@v0.37.6/rpc/jsonrpc/server/http_server.go:229 +0x26c
net/http.HandlerFunc.ServeHTTP(0x418a85?, {0x3946aa0?, 0xc001068000?}, 0xc001068001?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0x3941640?}, {0x3946aa0?, 0xc001068000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc00245f7a0, {0x3964920, 0xc00228c4e0})
	/usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 109
	/usr/local/go/src/net/http/server.go:3285 +0x4b4
: panic [cosmos/cosmos-sdk@v0.47.14-ics-lsm/baseapp/recovery.go:69] With gas wanted: '18446744073709551615' and gas used: '77686' : unknown request`

The issue seems to be caused by usage of uninitialized `fee` variable here:

```go
err := dfd.feegrantKeeper.UseGrantedFees(ctx, feeGranter, feePayer, sdk.NewCoins(fee), sdkTx.GetMsgs())
```

### Affected versions

- v1.0.1
- v1.0.1-sdk47

### LINKED ISSUE #115: [Bug]: Inaccurate gas estimations when feemarket is enabled
Some parts of the feemarket PostHandle() function (like [this](https://github.com/skip-mev/feemarket/blob/1252ec02c32c25c2bc4c32232c9fe7cfe8d57b0a/x/feemarket/post/fee.go#L181) and [this](https://github.com/skip-mev/feemarket/blob/1252ec02c32c25c2bc4c32232c9fe7cfe8d57b0a/x/feemarket/post/fee.go#L195) one) are not executed during transaction simulation, which causes the gas estimation to be wrong, since the gas spent there is not taken into account.

This has the following consequence: user runs transaction simulation in a wallet and receives some estimation of gas needed to execute the tx (let's say 80k gas units). It then uses gas adjustment multiplier (usually 1.3 by default) to set the gas limit on the tx, which would be 104k gas units in this case. When the wallet sends tx, it would fail during `deliverTx()` since it requires more gas than the specified gas limit (let's say the actual gas needed was 115k). Users have an option to increase the gas limit, but since the estimate given in the beginning is wrong, they need to guess what amount of gas would make their tx enter the block. If they specify very high gas limit, they would have to pay for gas that would not be actually spent.

The same problem exists with IBC relayers, which would need to use high gas multiplier in their configuration, and therefore pay much higher fees for creating light clients, connections, relaying packets, etc.

Here is an error thrown by the Hermes when trying to create a light client between two feemarket-enabled chains (using gas multiplier 1.5):

`ChainError("deliver_tx for 3780236541E37FEE56167162A089CCBBDA6FE75F83333A5FE988B1783DD32ABF reports error: code=Err(11), log=\"out of gas in location: Has; gasWanted: 131004, gasUsed: 131890: out of gas\"")`

### PR DESCRIPTION
**Pull request by aljo242**
Closes #114 
Closes #115

### CODE REVIEW

File: x/feemarket/post/fee.go [hunk 1]
```diff
@@ -89,6 +85,11 @@ func (dfd FeeMarketDeductDecorator) PostHandle(ctx sdk.Context, tx sdk.Tx, simul
 	feeCoin := feeCoins[0]
 	feeGas := int64(feeTx.GetGas())
 
+	var (
+		tip     = sdk.NewCoin(feeCoin.Denom, math.ZeroInt())
+		payCoin = feeCoin
+	)
```
Comment (aljo242) [inline x/feemarket/post/fee.go:91]: init to values so we avoid panics

File: x/feemarket/post/fee_test.go [hunk 2]
```diff
@@ -197,11 +191,31 @@ func TestPostHandle(t *testing.T) {
 			ExpPass:  false,
 			ExpErr:   sdkerrors.ErrInvalidGasLimit,
 		},
+		{
+			Name: "0 gas given should pass - simulate",
```
Comment (aljo242) [inline x/feemarket/post/fee_test.go:195]: adding tests for simulation cases

File: x/feemarket/post/fee.go [hunk 3]
```diff
@@ -177,7 +180,7 @@ func (dfd FeeMarketDeductDecorator) DeductFeeAndTip(ctx sdk.Context, sdkTx sdk.T
 	var events sdk.Events
 
 	// deduct the fees and tip
-	if !fee.Amount.IsNil() && !fee.IsZero() {
+	if !fee.IsNil() {
```
Comment (aljo242) [inline x/feemarket/post/fee.go:183]: change checks to `IsNil` so we will still make keeper calls when simulating

File: x/feemarket/post/fee.go [hunk 4]
```diff
@@ -212,10 +215,6 @@ func (dfd FeeMarketDeductDecorator) DeductFeeAndTip(ctx sdk.Context, sdkTx sdk.T
 // DeductCoins deducts coins from the given account.
 // Coins can be sent to the default fee collector (causes coins to be distributed to stakers) or sent to the feemarket fee collector account (causes coins to be burned).
 func DeductCoins(bankKeeper BankKeeper, ctx sdk.Context, acc sdk.AccountI, coins sdk.Coins, distributeFees bool) error {
-	if !coins.IsValid() {
```
Comment (MSalopek) [inline x/feemarket/post/fee.go:215]: Can you please elaborate this decision, it's not super clear to me.

**Review by MSalopek — APPROVED** [review]
Is there going to be a backport to v1.0.0-sdk47?

File: x/feemarket/post/fee.go [hunk 5]
```diff
@@ -107,7 +108,7 @@ func (dfd FeeMarketDeductDecorator) PostHandle(ctx sdk.Context, tx sdk.Tx, simul
 	}
 
 	ctx.Logger().Info("fee deduct post handle",
-		"fee", feeCoins,
+		"fee", payCoin,
```
Comment (MSalopek) [inline x/feemarket/post/fee.go:111]: `DeductFeeAndTip()` and `state.Update` are not counted towards the gas estimates when running sims, right?

Is that by design?

We've noticed this because we had to update the gas multiplier (adjustment) from 1.2 to 2.0 in our tests.

File: x/feemarket/post/fee.go (hunk 4 above)
Comment (aljo242) [reply x/feemarket/post/fee.go:215]: The coins are already guaranteed to be valid from how we are constructing them.  The only additional check this was doing was ensuring they are `non-zero`
